"""First revision

Revision ID: aae2f9cf1eba
Revises: 
Create Date: 2025-04-03 16:09:58.239040-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aae2f9cf1eba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CREATE', 'UPDATE', 'DELETE', name='updatetype').create(op.get_bind())
    sa.Enum('NAME', 'DESCRIPTION', 'QUANTITY', name='updatefield').create(op.get_bind())
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('product_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('update_field', postgresql.ENUM('NAME', 'DESCRIPTION', 'QUANTITY', name='updatefield', create_type=False), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('update_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_type', postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', name='updatetype', create_type=False), nullable=False),
    sa.Column('update_notes', sa.String(), nullable=True),
    sa.Column('update_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_history_id'), 'product_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_history_id'), table_name='product_history')
    op.drop_table('product_history')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    sa.Enum('NAME', 'DESCRIPTION', 'QUANTITY', name='updatefield').drop(op.get_bind())
    sa.Enum('CREATE', 'UPDATE', 'DELETE', name='updatetype').drop(op.get_bind())
    # ### end Alembic commands ###
