"""add timestamp

Revision ID: e311c377cd6b
Revises: daea4e409f73
Create Date: 2025-04-02 17:10:31.844217-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e311c377cd6b'
down_revision = 'daea4e409f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USED', 'RESTOCK', name='updatetype').create(op.get_bind())
    op.alter_column('inventory_history', 'update_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('inventory_history', 'update_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('USED', 'RESTOCK', name='updatetype'),
               existing_nullable=False,
               postgresql_using='update_type::updatetype')
    op.add_column('products', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.alter_column('inventory_history', 'update_type',
               existing_type=sa.Enum('USED', 'RESTOCK', name='updatetype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('inventory_history', 'update_timestamp',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    sa.Enum('USED', 'RESTOCK', name='updatetype').drop(op.get_bind())
    # ### end Alembic commands ###
